# Metadados da aplica칞칚o para o cat치logo DGB
name: "Anota칞칚o de Not칤cias - Fase 4"
description: "Interface de anota칞칚o manual de not칤cias governamentais para cria칞칚o de dataset de teste da 치rvore tem치tica"
owner:
  name: "Equipe Fase 4 - Valida칞칚o e Refinamento"
  email: "nitai@exemplo.com"
category: "admin"  # analytics, visualization, exploration, admin
tags:
  - "anota칞칚o"
  - "dataset"
  - "classifica칞칚o"
  - "치rvore tem치tica"
keywords: "anota칞칚o, not칤cias, classifica칞칚o, temas, dataset, ground truth"
icon: "游늶"
version: "1.0.0"
repository: "https://github.com/destaquesgovbr/themes-tree"
documentation: "https://github.com/destaquesgovbr/themes-tree/blob/main/_plan_refinamento/README.md"
